### ISSUE TITLE
SWRDevTools tab doesn't render anything

### ISSUE THREAD

**Issue by SukkaW** [koba04/swr-devtools#122]
Chrome 109.0.5414.119 on macOS 13.1 Beta (22C5050e)

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/40715044/225818846-a4b735fd-cc54-4d76-bb86-2d9b05bbb6df.png">
<img width="934" alt="image" src="https://user-images.githubusercontent.com/40715044/225818915-2b2bbfa2-04c6-4711-a029-1bdf1864289b.png">
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/40715044/225818785-07960e54-a886-4b48-94d7-204c23284965.png">

```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at chrome-extension://liidbicegefhheghhjbomajjaehnjned/app.js:2:266743
    at rs (chrome-extension://liidbicegefhheghhjbomajjaehnjned/app.js:2:143860)
    at xu (chrome-extension://liidbicegefhheghhjbomajjaehnjned/app.js:2:163982)
    at chrome-extension://liidbicegefhheghhjbomajjaehnjned/app.js:2:160586
    at x (chrome-extension://liidbicegefhheghhjbomajjaehnjned/app.js:2:190548)
    at MessagePort.T (chrome-extension://liidbicegefhheghhjbomajjaehnjned/app.js:2:191080)
```

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/40715044/225819201-9b26c9b1-f692-492a-a982-34f8d70d7b59.png">

**Comment by koba04** [comment]
Thank you! I'll take a look.
