### ISSUE TITLE
Extension causing pages to error.

### ISSUE THREAD

**Issue by ariesclark** [koba04/swr-devtools#125]
Try visiting https://dashboard.clerk.com/ with this extension enabled on Firefox, other browsers/websites not tested.

https://github.com/koba04/swr-devtools/assets/10256477/0e8c33bb-6ee5-4332-8cf9-70c7d04aea3e

**Comment by koba04** [comment]
Thank you for reporting it. I'll investigate it.

**Comment by waldothedeveloper** [comment]
I had to disable the extension as well I was getting the same error without even changing my code.

**Comment by panteliselef** [comment]
Hello @koba04 I'm part of the team at Clerk at hopefully I'll shed some light as what is happening.

## Background knowledge
The Clerk components load their own version of react-dom. Inside of these components swr is beeing used. I have managed to replicate this error only when swr is used both from the hosted app and the app mount the Clerk components.
In the case of our dashboard that is the case.

## Deep dive
I had a look at the code base of vercel/swr and swr-devtools (yours).
I found that there is "contract" between swr and swr-devtools which involves the usage of `window.__SWR_DEVTOOLS_REACT__` and `window.__SWR_DEVTOOLS_USE__`.

My understanding is that
1. window.__SWR_DEVTOOLS_USE__ will be populated as long as the extension is installed and enabled.
2. the app code runs and [`setupDevTools`](https://github.com/vercel/swr/blob/4d20bff6759d4478380963654a560a1cf9ae7be1/_internal/src/utils/devtools.ts#L12C1-L17C2) from swr runs as well, which populates `window.__SWR_DEVTOOLS_REACT__` with the react running from the app.
3. Then our components are being lazy loading and the swr code build within our components will again trigger the following line to execute [`window.__SWR_DEVTOOLS_REACT__ = React`](https://github.com/vercel/swr/blob/4d20bff6759d4478380963654a560a1cf9ae7be1/_internal/src/utils/devtools.ts#L12C1-L17C2).

**Comment by panteliselef** [comment]
I was thinking a similar approach. Would require PR to vercel/swr or is this something that can be solved from the devtools ?

**Comment by koba04** [comment]
Yeah, This approach requires to send a PR to `vercel/swr`.

**Comment by koba04** [comment]
I just published a new version (1.3.2) to fix this so please try it once the version is available.

**Comment by koba04** [comment]
I'll close this as closed, but if you had a similar behavior please file a new issue.
