### ISSUE TITLE
feat: waterfall chart

### ISSUE THREAD

**Issue by shuding** [koba04/swr-devtools#28]
Hi! I think it would be useful to have a new tab that shows all SWR hooks horizontally like waterfalls, similar to the Chrome DevTools network tab.

I'm happy to work on this feature and contribute a PR :)

**Comment by koba04** [comment]
@shuding 
Thank you for your feedback, it is useful and I love the feature👍 👍 👍 
 Currently, SWRDevTool inspects a setter of Cache, which means it's hard to build the timeline, so we would need more inspecting points in our middleware implementation.

**Comment by shuding** [comment]
Yeah, I think it's fine to add setter on top of the default cache. I'm also thinking about adding more options to SWR's core (e.g. `onDiscarded`, as a supplement to `onSuccess`, `onError`, `onLoadingSlow` and `onErrorRetry`, so the devtool can know when is a request result discarded because of race conditions).
