### ISSUE TITLE
Should we publish the Devtool Panel?

### ISSUE THREAD

**Issue by jellydn** [koba04/swr-devtools#30]
Hi @koba04 

Could you publish the private package and opt-out for PRODUCTION build as react-query devtools does?
https://react-query.tanstack.com/devtools

Let me what you thought about this idea. Thanks.

**Comment by koba04** [comment]
@jellydn 👍
I have a plan for this, so I'll make the package public.
> opt-out for PRODUCTION build as react-query devtools does
I'll consider that, thank you!
