### ISSUE TITLE
Chrome extension not working with Next.js v11

### ISSUE THREAD

**Issue by modbp** [koba04/swr-devtools#38]
Trying to get this working with Next.js 11+ and not having any luck.

I downloaded and ran the example site, but when I upgraded it from Next 10.0.6 -> 11.0.0 the Chrome extension stopped working (it just shows "Haven't received any cache data from SWRDevTools"). The React panel continues to work as expected after the upgrade. Tried to figure out what is going wrong, but no luck.

Love the promise of this package! Thanks for all of your work on it, it's the biggest thing I'm missing with SWR.

**Comment by koba04** [comment]
Thank you for reporting the issue! I'll test it on Next.js v11 and v12.

**Comment by koba04** [comment]
I've confirmed that this has been fixed with `webpack5: false` in `next.config.js`, so I have to make `swr-devtools` webpack v5 compatible.

**Comment by koba04** [comment]
The middleware of SWRDevtools seems not to be called with Next.js v11.

**Comment by koba04** [comment]
@modbp I've fixed it and released it as v0.4.0, so could you test the version?
https://github.com/koba04/swr-devtools/releases/tag/v0.4.0

If your application still doesn't work, please confirm that it only includes single `swr` in your bundle.

**Comment by modbp** [comment]
Hi @koba04, looks like it's all worrying now on my end. 🎉🎉🎉

Thank you so much for addressing this issue!
