### ISSUE TITLE
Feat: Add manual dark mode support

### ISSUE THREAD

**Issue by dev-afzalansari** [koba04/swr-devtools#91]
While reading the source code I played around it a little bit and added dark mode support to the panel. I think it will be more convenient to let users choose the theme of the panel on their own instead of only depending on system's theme.

[color-mode-demo.webm](https://user-images.githubusercontent.com/89535738/202842292-b9878983-40c9-428f-8440-286231f14b89.webm)

Currently swr-devtools-panel depends on system's preference to enable dark mode manual dark mode has option for that too.

@koba04, should i open a PR for this.

**Comment by koba04** [comment]
@dev-afzalansari That looks amazing!!! 👍 👍
